---
title: "Getting & Cleaning Data Course Project - Codebook"
author: "Neil Kutty github.com/sampsonsimpson"
date: "June 24, 2016"
output: html_document
---

<h3> Codebook </h3>
<ul><b> Feature Variables Descriptions </ul></b>
Data Set Information:

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

Attribute Information:

For each record in the dataset it is provided: 
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.


 [1] "tBodyAcc Mean -X"               "tBodyAcc Mean -Y"               "tBodyAcc Mean -Z"              
 <br>[4] "tBodyAcc StdDev -X"             "tBodyAcc StdDev -Y"             "tBodyAcc StdDev -Z"            
 <br>[7] "tGravityAcc Mean -X"            "tGravityAcc Mean -Y"            "tGravityAcc Mean -Z"           
<br>[10] "tGravityAcc StdDev -X"          "tGravityAcc StdDev -Y"          "tGravityAcc StdDev -Z"         
<br>[13] "tBodyAccJerk Mean -X"           "tBodyAccJerk Mean -Y"           "tBodyAccJerk Mean -Z"          
<br>[16] "tBodyAccJerk StdDev -X"         "tBodyAccJerk StdDev -Y"         "tBodyAccJerk StdDev -Z"        
<br>[19] "tBodyGyro Mean -X"              "tBodyGyro Mean -Y"              "tBodyGyro Mean -Z"             
<br>[22] "tBodyGyro StdDev -X"            "tBodyGyro StdDev -Y"            "tBodyGyro StdDev -Z"           
<br>[25] "tBodyGyroJerk Mean -X"          "tBodyGyroJerk Mean -Y"          "tBodyGyroJerk Mean -Z"         
<br>[28] "tBodyGyroJerk StdDev -X"        "tBodyGyroJerk StdDev -Y"        "tBodyGyroJerk StdDev -Z"       
<br>[31] "tBodyAccMag Mean "              "tBodyAccMag StdDev "            "tGravityAccMag Mean "          
<br>[34] "tGravityAccMag StdDev "         "tBodyAccJerkMag Mean "          "tBodyAccJerkMag StdDev "       
<br>[37] "tBodyGyroMag Mean "             "tBodyGyroMag StdDev "           "tBodyGyroJerkMag Mean "        
<br>[40] "tBodyGyroJerkMag StdDev "       "fBodyAcc Mean -X"               "fBodyAcc Mean -Y"              
<br>[43] "fBodyAcc Mean -Z"               "fBodyAcc StdDev -X"             "fBodyAcc StdDev -Y"            
<br>[46] "fBodyAcc StdDev -Z"             "fBodyAcc MeanFreq -X"           "fBodyAcc MeanFreq -Y"          
<br>[49] "fBodyAcc MeanFreq -Z"           "fBodyAccJerk Mean -X"           "fBodyAccJerk Mean -Y"          
<br>[52] "fBodyAccJerk Mean -Z"           "fBodyAccJerk StdDev -X"         "fBodyAccJerk StdDev -Y"        
<br>[55] "fBodyAccJerk StdDev -Z"         "fBodyAccJerk MeanFreq -X"       "fBodyAccJerk MeanFreq -Y"      
<br>[58] "fBodyAccJerk MeanFreq -Z"       "fBodyGyro Mean -X"              "fBodyGyro Mean -Y"             
<br>[61] "fBodyGyro Mean -Z"              "fBodyGyro StdDev -X"            "fBodyGyro StdDev -Y"           
<br>[64] "fBodyGyro StdDev -Z"            "fBodyGyro MeanFreq -X"          "fBodyGyro MeanFreq -Y"         
<br>[67] "fBodyGyro MeanFreq -Z"          "fBodyAccMag Mean "              "fBodyAccMag StdDev "           
<br>[70] "fBodyAccMag MeanFreq "          "fBodyBodyAccJerkMag Mean "      "fBodyBodyAccJerkMag StdDev "   
<br>[73] "fBodyBodyAccJerkMag MeanFreq "  "fBodyBodyGyroMag Mean "         "fBodyBodyGyroMag StdDev "      
<br>[76] "fBodyBodyGyroMag MeanFreq "     "fBodyBodyGyroJerkMag Mean "     "fBodyBodyGyroJerkMag StdDev "  
<br>[79] "fBodyBodyGyroJerkMag MeanFreq "

<ul><b> Environment Variables Descriptions </b></ul>
<hr>

**`features`** is a table containing the descriptive names of the measurements that they are included in the test and train datasets.

```
str(features)
'data.frame':	561 obs. of  2 variables:
 $ V1: int  1 2 3 4 5 6 7 8 9 10 ...
 $ V2: Factor w/ 477 levels "angle(tBodyAccJerkMean),gravityMean)",..: 243 244 245 250 251 252 237 238 239 240 ...
```
<br>
**`features`** is used to create **`featuresLite`** a vector with the rows of only those feature names that contain 'Mean' and 'Std'.  
<br>
**`featureNames`** is a character vector created from subsetting the
**`features`** descriptive names column for only the names we want (those containing 'Mean' and 'Std'). We end up with only 79 of the original 561 features that we actually need the data from.  This will make reading in the data a lot easier. We then clean it to remove the extra characters and we have our list of feature names.

```
str(featureNames)
chr [1:79] "tBodyAcc Mean -X" "tBodyAcc Mean -Y" ...
```
<br>
**`activityLabels`** is a data frame with the activity labels. The name of the ID column is named `activityID` to create a common column name across the tables we intend to later `merge()`

```
str(activityLabels)
'data.frame':	6 obs. of  2 variables:
 $ activityID: int  1 2 3 4 5 6
 $ activity  : Factor w/ 6 levels "LAYING","SITTING",..: 4 6 5 2 3 1
```

<br>
**`subjectTrain`** - data frame with the subjectID column.
```
str(subjectTrain)
'data.frame':	7352 obs. of  1 variable:
 $ subjectID: int  1 1 1 1 1 1 1 1 1 1 ...
```

<br>
**`xtrain`**  - data frame with values for of the features for a particular subject and activity for the train data.
```
First Five Lines
str(xtrain)
'data.frame':	7352 obs. of  79 variables:
 $ tBodyAcc Mean -X              : num  0.289 0.278 0.28 0.279 0.277 ...
 $ tBodyAcc Mean -Y              : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
 $ tBodyAcc Mean -Z              : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
 $ tBodyAcc StdDev -X            : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
 $ tBodyAcc StdDev -Y            : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
 ...
```

<br>
**`ytrain`** - data frame with the activityID column for the train data.
```
str(ytrain)
'data.frame':	7352 obs. of  1 variable:
 $ activityID: int  5 5 5 5 5 5 5 5 5 5 ...
```

<br>
**`trainSet`** - data frame created by combining the `subjectTrain`,`ytrain`, and `xtrain` dataframes using `cbind()`.
```
First Five Lines
str(trainSet)
'data.frame':	7352 obs. of  81 variables:
 $ subjectID                     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ activityID                    : int  5 5 5 5 5 5 5 5 5 5 ...
 $ tBodyAcc Mean -X              : num  0.289 0.278 0.28 0.279 0.277 ...
 $ tBodyAcc Mean -Y              : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
 $ tBodyAcc Mean -Z              : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
 ...
```


<br>
**`subjectTest`** - data frame with the subjectID column for the test data.
```
str(subjectTest)
'data.frame':	2947 obs. of  1 variable:
 $ subjectID: int  2 2 2 2 2 2 2 2 2 2 ...
```

<br>
**`xtest`**  - data frame with values for of the features for a particular subject and activity for the test data.
```
First Five Lines
str(xtest)
'data.frame':	2947 obs. of  79 variables:
 $ tBodyAcc Mean -X              : num  0.257 0.286 0.275 0.27 0.275 ...
 $ tBodyAcc Mean -Y              : num  -0.0233 -0.0132 -0.0261 -0.0326 -0.0278 ...
 $ tBodyAcc Mean -Z              : num  -0.0147 -0.1191 -0.1182 -0.1175 -0.1295 ...
 $ tBodyAcc StdDev -X            : num  -0.938 -0.975 -0.994 -0.995 -0.994 ...
 $ tBodyAcc StdDev -Y            : num  -0.92 -0.967 -0.97 -0.973 -0.967 ...
 ...
```

<br>
**`ytest`** - data frame with the activityID column for the test data..
```
str(ytest)
'data.frame':	2947 obs. of  1 variable:
 $ activityID: int  5 5 5 5 5 5 5 5 5 5 ...
```

<br>
**`testSet`** - data frame created by combining the `subjectTest`,`ytest`, and `xtest` dataframes using `cbind()`.
```
First Five Lines
str(testSet)
'data.frame':	2947 obs. of  81 variables:
 $ subjectID                     : int  2 2 2 2 2 2 2 2 2 2 ...
 $ activityID                    : int  5 5 5 5 5 5 5 5 5 5 ...
 $ tBodyAcc Mean -X              : num  0.257 0.286 0.275 0.27 0.275 ...
 $ tBodyAcc Mean -Y              : num  -0.0233 -0.0132 -0.0261 -0.0326 -0.0278 ...
 $ tBodyAcc Mean -Z              : num  -0.0147 -0.1191 -0.1182 -0.1175 -0.1295 ...
 ...
```

<br>
**`fullSet`** - created by first joining the `trainSet` and `testSet` rows and then merging the result with the `activityLabels` table for the descriptive activity. 
```
 str(fullSet)
'data.frame':	10299 obs. of  82 variables:
 $ activityID                    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ activity                      : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ subjectID                     : int  28 28 28 28 28 28 28 28 28 28 ...
 $ tBodyAcc Mean -X              : num  0.308 0.168 0.343 0.31 0.17 ...
 $ tBodyAcc Mean -Y              : num  -0.00617 -0.01862 -0.02722 -0.04363 -0.00886 ...
```

<br>
**`cleanSet`** - created by gathering the columns of `fullSet` into a long table format.
```
str(cleanSet)
'data.frame':	813621 obs. of  5 variables:
 $ activityID: int  1 1 1 1 1 1 1 1 1 1 ...
 $ activity  : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ subjectID : int  28 28 28 28 28 28 28 28 28 28 ...
 $ key       : chr  "tBodyAcc Mean -X" "tBodyAcc Mean -X" "tBodyAcc Mean -X" "tBodyAcc Mean -X" ...
 $ value     : num  0.308 0.168 0.343 0.31 0.17 ...
```

<br>
**`tidySet`** - created by utilizing a chain operation of `dplyr` and `tidyr` functions:
```{r tidySet, eval=FALSE}
#create tidy set by
# separating the feature column into the three delimited parts
#    and labeling the new cols appropriately: 'feature','measure','XYZ'
# grouping by all relevant columns
# summarising by the group above for the average of all values
# spreading the dataset by the newly created 'measure' column
tidySet <- cleanSet %>%
    separate(key, into=c('feature','measure','XYZ'), sep = ' ') %>%
    group_by(feature, activityID, activity, subjectID, measure) %>%
    summarise(Value = mean(value)) %>%
    spread(measure, Value)

str(tidySet)
'data.frame':	3060 obs. of  7 variables:
 $ feature   : chr  "fBodyAcc" "fBodyAcc" "fBodyAcc" "fBodyAcc" ...
 $ activityID: int  1 1 1 1 1 1 1 1 1 1 ...
 $ activity  : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ subjectID : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Mean      : num  -0.148 -0.274 -0.27 -0.402 -0.256 ...
 $ MeanFreq  : num  -1.49e-02 4.06e-02 -5.85e-06 -6.83e-02 -9.99e-02 ...
 $ StdDev    : num  -0.181 -0.361 -0.309 -0.381 -0.246 ...
```



<br>
**tidySet output**
 
 `$feature`
 <br>[1] "fBodyAcc"             "fBodyAccJerk"         "fBodyAccMag"          "fBodyBodyAccJerkMag"  "fBodyBodyGyroJerkMag" "fBodyBodyGyroMag"    
 <br>[7] "fBodyGyro"            "tBodyAcc"             "tBodyAccJerk"         "tBodyAccJerkMag"      "tBodyAccMag"          "tBodyGyro"           
<br>[13] "tBodyGyroJerk"        "tBodyGyroJerkMag"     "tBodyGyroMag"         "tGravityAcc"          "tGravityAccMag"

 `$activity`
 <br>LAYING SITTING STANDING WALKING WALKING_DOWNSTAIRS WALKING_UPSTAIRS
 
 `MEASURES`
 <br>`Mean MeanFreq StdDev`
 <br>
 **note we drop the direction XYZ segment from the cleanSet to aggregate by Subject > Activity > Feature only for the TidySet**